/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package android_talking_software.development.talking_tap_twice;

public final class R {
    public static final class attr {
        /** <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int defaultMethod=0x7f010004;
        /** <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int defaultSelected=0x7f010005;
        /** <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int label=0x7f010001;
        /** <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int method=0x7f010000;
        /** <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int pronounciationDictionaryEntries=0x7f010006;
        /** <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int tapped=0x7f010002;
        /** <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int whenSelected=0x7f010003;
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int angle_x_checkbox=0x7f05001e;
        public static final int angle_z_checkbox=0x7f05001f;
        public static final int at_x_checkbox=0x7f05001c;
        public static final int at_z_checkbox=0x7f05001d;
        public static final int backspace_button=0x7f050014;
        public static final int cancel_button=0x7f050023;
        public static final int clear_button=0x7f050015;
        public static final int decimal_button=0x7f050013;
        public static final int display=0x7f050001;
        public static final int divide_button=0x7f050005;
        public static final int eight_button=0x7f050007;
        public static final int equals_button=0x7f050016;
        public static final int exit_button=0x7f050019;
        public static final int exponent_button=0x7f050004;
        public static final int five_button=0x7f05000b;
        public static final int four_button=0x7f05000a;
        public static final int from_x_checkbox=0x7f050020;
        public static final int from_z_checkbox=0x7f050021;
        public static final int left_paren_button=0x7f050002;
        public static final int level=0x7f050017;
        public static final int minus_button=0x7f05000d;
        public static final int multiply_button=0x7f050009;
        public static final int nine_button=0x7f050008;
        public static final int okay_button=0x7f050022;
        public static final int one_button=0x7f05000e;
        public static final int options_button=0x7f050018;
        public static final int plus_button=0x7f050011;
        public static final int right_paren_button=0x7f050003;
        public static final int rotation_x_checkbox=0x7f05001a;
        public static final int rotation_z_checkbox=0x7f05001b;
        public static final int seven_button=0x7f050006;
        public static final int six_button=0x7f05000c;
        public static final int three_button=0x7f050010;
        public static final int title=0x7f050000;
        public static final int two_button=0x7f05000f;
        public static final int zero_button=0x7f050012;
    }
    public static final class layout {
        public static final int calculator=0x7f030000;
        public static final int level=0x7f030001;
        public static final int main4calculator=0x7f030002;
        public static final int main4level=0x7f030003;
        public static final int options=0x7f030004;
    }
    public static final class raw {
        public static final int click=0x7f040000;
    }
    public static final class styleable {
        /** Attributes that can be used with a ButtonTTT.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #ButtonTTT_label android_talking_software.development.talking_tap_twice:label}</code></td><td></td></tr>
           <tr><td><code>{@link #ButtonTTT_method android_talking_software.development.talking_tap_twice:method}</code></td><td></td></tr>
           <tr><td><code>{@link #ButtonTTT_tapped android_talking_software.development.talking_tap_twice:tapped}</code></td><td></td></tr>
           <tr><td><code>{@link #ButtonTTT_whenSelected android_talking_software.development.talking_tap_twice:whenSelected}</code></td><td></td></tr>
           </table>
           @see #ButtonTTT_label
           @see #ButtonTTT_method
           @see #ButtonTTT_tapped
           @see #ButtonTTT_whenSelected
         */
        public static final int[] ButtonTTT = {
            0x7f010000, 0x7f010001, 0x7f010002, 0x7f010003
        };
        /**
          <p>This symbol is the offset where the {@link android_talking_software.development.talking_tap_twice.R.attr#label}
          attribute's value can be found in the {@link #ButtonTTT} array.


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android:label
        */
        public static final int ButtonTTT_label = 1;
        /**
          <p>This symbol is the offset where the {@link android_talking_software.development.talking_tap_twice.R.attr#method}
          attribute's value can be found in the {@link #ButtonTTT} array.


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android:method
        */
        public static final int ButtonTTT_method = 0;
        /**
          <p>This symbol is the offset where the {@link android_talking_software.development.talking_tap_twice.R.attr#tapped}
          attribute's value can be found in the {@link #ButtonTTT} array.


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android:tapped
        */
        public static final int ButtonTTT_tapped = 2;
        /**
          <p>This symbol is the offset where the {@link android_talking_software.development.talking_tap_twice.R.attr#whenSelected}
          attribute's value can be found in the {@link #ButtonTTT} array.


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android:whenSelected
        */
        public static final int ButtonTTT_whenSelected = 3;
        /** Attributes that can be used with a CheckBoxTTT.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #CheckBoxTTT_label android_talking_software.development.talking_tap_twice:label}</code></td><td></td></tr>
           <tr><td><code>{@link #CheckBoxTTT_method android_talking_software.development.talking_tap_twice:method}</code></td><td></td></tr>
           <tr><td><code>{@link #CheckBoxTTT_tapped android_talking_software.development.talking_tap_twice:tapped}</code></td><td></td></tr>
           <tr><td><code>{@link #CheckBoxTTT_whenSelected android_talking_software.development.talking_tap_twice:whenSelected}</code></td><td></td></tr>
           </table>
           @see #CheckBoxTTT_label
           @see #CheckBoxTTT_method
           @see #CheckBoxTTT_tapped
           @see #CheckBoxTTT_whenSelected
         */
        public static final int[] CheckBoxTTT = {
            0x7f010000, 0x7f010001, 0x7f010002, 0x7f010003
        };
        /**
          <p>This symbol is the offset where the {@link android_talking_software.development.talking_tap_twice.R.attr#label}
          attribute's value can be found in the {@link #CheckBoxTTT} array.


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android:label
        */
        public static final int CheckBoxTTT_label = 1;
        /**
          <p>This symbol is the offset where the {@link android_talking_software.development.talking_tap_twice.R.attr#method}
          attribute's value can be found in the {@link #CheckBoxTTT} array.


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android:method
        */
        public static final int CheckBoxTTT_method = 0;
        /**
          <p>This symbol is the offset where the {@link android_talking_software.development.talking_tap_twice.R.attr#tapped}
          attribute's value can be found in the {@link #CheckBoxTTT} array.


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android:tapped
        */
        public static final int CheckBoxTTT_tapped = 2;
        /**
          <p>This symbol is the offset where the {@link android_talking_software.development.talking_tap_twice.R.attr#whenSelected}
          attribute's value can be found in the {@link #CheckBoxTTT} array.


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android:whenSelected
        */
        public static final int CheckBoxTTT_whenSelected = 3;
        /** Attributes that can be used with a LinearLayoutTTT.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #LinearLayoutTTT_defaultMethod android_talking_software.development.talking_tap_twice:defaultMethod}</code></td><td></td></tr>
           <tr><td><code>{@link #LinearLayoutTTT_defaultSelected android_talking_software.development.talking_tap_twice:defaultSelected}</code></td><td></td></tr>
           <tr><td><code>{@link #LinearLayoutTTT_pronounciationDictionaryEntries android_talking_software.development.talking_tap_twice:pronounciationDictionaryEntries}</code></td><td></td></tr>
           </table>
           @see #LinearLayoutTTT_defaultMethod
           @see #LinearLayoutTTT_defaultSelected
           @see #LinearLayoutTTT_pronounciationDictionaryEntries
         */
        public static final int[] LinearLayoutTTT = {
            0x7f010004, 0x7f010005, 0x7f010006
        };
        /**
          <p>This symbol is the offset where the {@link android_talking_software.development.talking_tap_twice.R.attr#defaultMethod}
          attribute's value can be found in the {@link #LinearLayoutTTT} array.


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android:defaultMethod
        */
        public static final int LinearLayoutTTT_defaultMethod = 0;
        /**
          <p>This symbol is the offset where the {@link android_talking_software.development.talking_tap_twice.R.attr#defaultSelected}
          attribute's value can be found in the {@link #LinearLayoutTTT} array.


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android:defaultSelected
        */
        public static final int LinearLayoutTTT_defaultSelected = 1;
        /**
          <p>This symbol is the offset where the {@link android_talking_software.development.talking_tap_twice.R.attr#pronounciationDictionaryEntries}
          attribute's value can be found in the {@link #LinearLayoutTTT} array.


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android:pronounciationDictionaryEntries
        */
        public static final int LinearLayoutTTT_pronounciationDictionaryEntries = 2;
        /** Attributes that can be used with a TextViewTTT.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #TextViewTTT_label android_talking_software.development.talking_tap_twice:label}</code></td><td></td></tr>
           <tr><td><code>{@link #TextViewTTT_method android_talking_software.development.talking_tap_twice:method}</code></td><td></td></tr>
           <tr><td><code>{@link #TextViewTTT_tapped android_talking_software.development.talking_tap_twice:tapped}</code></td><td></td></tr>
           <tr><td><code>{@link #TextViewTTT_whenSelected android_talking_software.development.talking_tap_twice:whenSelected}</code></td><td></td></tr>
           </table>
           @see #TextViewTTT_label
           @see #TextViewTTT_method
           @see #TextViewTTT_tapped
           @see #TextViewTTT_whenSelected
         */
        public static final int[] TextViewTTT = {
            0x7f010000, 0x7f010001, 0x7f010002, 0x7f010003
        };
        /**
          <p>This symbol is the offset where the {@link android_talking_software.development.talking_tap_twice.R.attr#label}
          attribute's value can be found in the {@link #TextViewTTT} array.


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android:label
        */
        public static final int TextViewTTT_label = 1;
        /**
          <p>This symbol is the offset where the {@link android_talking_software.development.talking_tap_twice.R.attr#method}
          attribute's value can be found in the {@link #TextViewTTT} array.


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android:method
        */
        public static final int TextViewTTT_method = 0;
        /**
          <p>This symbol is the offset where the {@link android_talking_software.development.talking_tap_twice.R.attr#tapped}
          attribute's value can be found in the {@link #TextViewTTT} array.


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android:tapped
        */
        public static final int TextViewTTT_tapped = 2;
        /**
          <p>This symbol is the offset where the {@link android_talking_software.development.talking_tap_twice.R.attr#whenSelected}
          attribute's value can be found in the {@link #TextViewTTT} array.


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name android:whenSelected
        */
        public static final int TextViewTTT_whenSelected = 3;
    };
}
